//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organiziranje_sportskog_događaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupa
    {
        public int id_grupa { get; set; }
        public string oznaka { get; set; }
        public int postignuti_golovi { get; set; }
        public int primljeni_golovi { get; set; }
        public int pobjede { get; set; }
        public int porazi { get; set; }
        public int remi { get; set; }
        public int id_turnir { get; set; }
        public int id_tim { get; set; }
    
        public virtual tim tim { get; set; }
        public virtual turnir turnir { get; set; }
    }
}
