//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organiziranje_sportskog_događaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class organizacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public organizacija()
        {
            this.dogadajs = new HashSet<dogadaj>();
        }
    
        public int id_organizacija { get; set; }
        public string naziv { get; set; }
        public string OIB { get; set; }
        public string kontakt_broj { get; set; }
        public string email { get; set; }
        public string adresa { get; set; }
        public string korisnicko_ime { get; set; }
        public string lozinka { get; set; }
        public string opis { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dogadaj> dogadajs { get; set; }
    }
}
