//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organiziranje_sportskog_događaja
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PI2231_DBEntities : DbContext
    {
        public PI2231_DBEntities()
            : base("name=PI2231_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<dogadaj> dogadajs { get; set; }
        public virtual DbSet<grupa> grupas { get; set; }
        public virtual DbSet<korisnik> korisniks { get; set; }
        public virtual DbSet<organizacija> organizacijas { get; set; }
        public virtual DbSet<raspored_utakmica> raspored_utakmica { get; set; }
        public virtual DbSet<sport> sports { get; set; }
        public virtual DbSet<statistika_igraca> statistika_igraca { get; set; }
        public virtual DbSet<status_dogadaja> status_dogadaja { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tim> tims { get; set; }
        public virtual DbSet<turnir> turnirs { get; set; }
        public virtual DbSet<uloga_korisnika> uloga_korisnika { get; set; }
    }
}
