//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organiziranje_sportskog_događaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class raspored_utakmica
    {
        public int id_utakmica { get; set; }
        public string tim_jedan { get; set; }
        public string tim_dva { get; set; }
        public int broj_golova_prvog_tima { get; set; }
        public int broj_golova_drugog_tima { get; set; }
        public int id_turnir { get; set; }
        public string faza { get; set; }
    
        public virtual turnir turnir { get; set; }
    }
}
