//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Organiziranje_sportskog_događaja
{
    using System;
    using System.Collections.Generic;
    
    public partial class statistika_igraca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public statistika_igraca()
        {
            this.turnirs = new HashSet<turnir>();
        }
    
        public int igrac_id { get; set; }
        public Nullable<int> pogodak { get; set; }
        public Nullable<int> asistencija { get; set; }
        public Nullable<int> skok { get; set; }
        public Nullable<int> prekrsaj { get; set; }
        public int statistika_igraca_id { get; set; }
    
        public virtual korisnik korisnik { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turnir> turnirs { get; set; }
    }
}
